import { describe, expect, it } from 'vitest'
import type { ReceivedResponse, RunResult } from '@schwabyio/gravity-core'
import { htmlReport, runTime, type HtmlCollection, type HtmlRun } from './html.js'
import type { CollectionTally } from './report.js'

const response = (over: Partial<ReceivedResponse> = {}): ReceivedResponse => ({
  status: 200,
  statusText: 'OK',
  url: 'http://x/items',
  headers: [{ name: 'content-type', value: 'application/json' }],
  body: '{"id":1}',
  bodyKind: 'json',
  sizeBytes: 8,
  redirectCount: 0,
  timings: { startedAt: 0, ttfbMs: 5, totalMs: 7 },
  ...over
})

const result = (name: string, over: Partial<RunResult> = {}): RunResult => ({
  item: { path: 'collections/a.yml', name, seq: null },
  request: {
    method: 'GET',
    url: 'http://x/items',
    headers: [{ name: 'Accept', value: '*/*' }],
    body: null
  },
  response: response(),
  assertions: [{ name: 'Status is 200', status: 'pass' }],
  error: null,
  status: 'pass',
  durationMs: 9,
  ...over
})

const tallyOf = (passed: boolean, over: Partial<CollectionTally> = {}): CollectionTally => ({
  id: 'x',
  passed,
  durationMs: 10,
  steps: { total: 1, passed: passed ? 1 : 0, failed: passed ? 0 : 1, errored: 0, skipped: 0 },
  assertions: { total: 1, passed: passed ? 1 : 0, failed: passed ? 0 : 1 },
  skipped: false,
  error: null,
  problems: [],
  ...over
})

const collection = (
  id: string,
  results: RunResult[],
  passed = true,
  tally: Partial<CollectionTally> = {}
): HtmlCollection => ({
  id,
  file: `collections/${id}.yml`,
  startedAt: 0,
  durationMs: 10,
  tally: { ...tallyOf(passed, tally), id },
  outcome: {
    ok: true,
    summary: {
      total: results.length,
      passed: 0,
      failed: 0,
      errored: 0,
      skipped: 0,
      durationMs: 10,
      results
    },
    steps: results.map((_, index) => ({ index, line: index + 3 })),
    data: null
  }
})

const run = (...collections: HtmlCollection[]): HtmlRun => ({
  project: 'Shop',
  root: '/work/shop',
  version: '1.2.3',
  environment: 'staging',
  concurrency: 4,
  timeoutCollection: 60000,
  tags: [],
  bail: false,
  excluded: ['legacy'],
  untagged: 0,
  startedAt: 0,
  durationMs: 1234,
  collections
})

const pages = (r: HtmlRun) => new Map(htmlReport(r).map((p) => [p.path, p.html]))

/** The one page a run of these results writes for collection `a`. */
const pageFor = (...results: RunResult[]) => pages(run(collection('a', results))).get('a.html')!

describe('htmlReport', () => {
  it('is a summary page and a page per collection, loading nothing and naming no folder', () => {
    const report = pages(
      run(collection('smoke', [result('list')]), collection('sessions', [result('create')]))
    )
    expect([...report.keys()]).toEqual(['summary.html', 'smoke.html', 'sessions.html'])
    for (const html of report.values()) {
      expect(html).toMatch(/^<!doctype html>/)
      expect(html).not.toMatch(/<(link|script|img|iframe)[^>]+(href|src)="?https?:/)
      // The version leads to the repo; where the run was is left out.
      expect(html).toContain(
        'Generated by <a href="https://github.com/schwabyio/gravity" target="_blank" rel="noopener noreferrer"'
      )
      expect(html).toContain('gta 1.2.3')
      expect(html).not.toContain('/work/shop')
      // Light or dark, with the system.
      expect(html).toContain('@media (prefers-color-scheme:dark)')
    }
  })

  it('lays the summary out as Settings, Summary Stats, Results Overview, then what did not run', () => {
    const summary = pages(run(collection('smoke', [result('list')]))).get('summary.html')!
    expect(summary).toContain('<title>PASSED · Shop · gta Summary Results</title>')
    expect(summary).toContain(
      '<span class="pill solid s-passed">passed</span><h1>Shop <span class="kind">· Summary Results</span></h1>'
    )
    expect(summary).toContain('<h2>Settings</h2>')
    expect(summary).toContain('<div><dt>Environment</dt><dd>staging</dd></div>')
    expect(summary).toContain(
      '<div><dt>Collection Timeout</dt><dd>60,000 ms <span class="dim">· 1 min</span></dd></div>'
    )
    expect(summary).toContain('<h2>Summary Stats</h2>')
    // The run's time is in the stats, in words and exact on hover; the head says when it ran.
    expect(summary).toContain(
      '<div class="stat-label">Total Run Time</div><div class="stat-time" title="1,234 ms">1.23&nbsp;seconds</div>'
    )
    expect(summary).toMatch(/<div class="meta"><span>[^<]+<\/span><\/div>/)
    expect(summary.indexOf('Total Run Time')).toBeLessThan(summary.indexOf('Results Overview'))
    expect(summary).toContain('<h2>Results Overview</h2>')
    expect(summary).toContain('<th>Collection ID</th>')
    // Each collection's page opens in a tab of its own, the summary left where it was.
    expect(summary).toContain('<a href="smoke.html" target="_blank" rel="noopener">smoke</a>')
    expect(summary).toContain('data-hide="passed" aria-pressed="true"')
    // A search box narrows the rows, matched on each one's id.
    expect(summary).toContain('placeholder="Search collections"')
    // The search by the title and the chips at the far end, as on a collection page.
    expect(summary).toMatch(
      /<h2>Results Overview<\/h2><input type="search" class="search" placeholder="Search collections"[^>]*><div class="tools-end"><button type="button" class="chip s-passed"/
    )
    expect(summary).toContain('<tr class="s-passed" data-status="passed" data-search="smoke">')
    // Nothing failed, so there is nothing for a Failed chip to hide.
    expect(summary).not.toContain('data-hide="failed"')

    // Excluded is a count in Settings that leads to the list, at the bottom.
    expect(summary).toContain(
      '<div><dt>Excluded</dt><dd><a href="#not-run">1 collection ↓</a></dd></div>'
    )
    expect(summary).toContain(
      '<section class="card" id="not-run"><div class="card-h"><h2>Not Run</h2>'
    )
    expect(summary).toContain('<ul class="excluded"><li>legacy</li></ul>')
    expect(summary.indexOf('id="not-run"')).toBeGreaterThan(summary.indexOf('Results Overview'))
  })

  it('leaves the Not Run list out when nothing was, and lists what tags left out when they did', () => {
    const nothing = pages({ ...run(collection('a', [result('x')])), excluded: [] }).get(
      'summary.html'
    )!
    expect(nothing).toContain('<dt>Excluded</dt><dd><span class="dim">none</span></dd>')
    expect(nothing).not.toContain('id="not-run"')

    const tagged = pages({ ...run(collection('a', [result('x')])), excluded: [], untagged: 2 }).get(
      'summary.html'
    )!
    expect(tagged).toContain('<dt>Left Out By Tags</dt><dd><a href="#not-run">2 collections ↓</a>')
    expect(tagged).toContain(
      '<h3 class="group-h">Left out by tags <span class="dim">· 2 collections</span></h3>'
    )
  })

  it('counts a skipped collection on its own, and rates what ran, rounding down', () => {
    const summary = pages(
      run(
        collection('a', [result('x')]),
        collection('b', [result('x')]),
        collection('c', [result('x')], false),
        collection('d', [result('x', { status: 'skipped' })], true, {
          skipped: true,
          steps: { total: 1, passed: 0, failed: 0, errored: 0, skipped: 1 },
          assertions: { total: 0, passed: 0, failed: 0 }
        })
      )
    ).get('summary.html')!
    expect(summary).toContain(
      '<div class="legend"><span class="s-passed"><i></i>2 passed</span><span class="s-failed"><i></i>1 failed</span><span class="s-skipped"><i></i>1 skipped</span></div>'
    )
    // Two of the three that ran passed: 66%, not 67% and never 100% while one failed.
    expect(summary).toContain('<div class="ring" title="2 of 3 that ran passed">')
    expect(summary).toContain('<b>66%</b></div><div><div class="stat-label">Collections</div>')
    expect(summary).toContain('<tr class="s-skipped" data-status="skipped" data-search="d">')
    expect(summary).toContain('<span class="pill s-skipped">skipped</span>')
  })

  it('lets a long collection id wrap at its underscores, so the overview fits its card', () => {
    const summary = pages(run(collection('XTEST_DEMO_DATA_FILE', [result('x')]))).get(
      'summary.html'
    )!
    expect(summary).toContain(
      '<a href="XTEST_DEMO_DATA_FILE.html" target="_blank" rel="noopener">XTEST_<wbr>DEMO_<wbr>DATA_<wbr>FILE</a>'
    )
    // Searched as written.
    expect(summary).toContain('data-search="xtest_demo_data_file"')
  })

  it('marks the thousands in every number its stats show', () => {
    const big = collection('big', [result('x')], false, {
      steps: { total: 12_345, passed: 12_000, failed: 345, errored: 0, skipped: 0 },
      assertions: { total: 1_000_000, passed: 999_999, failed: 1 }
    })
    const summary = pages({ ...run(big), durationMs: 4_000_000 }).get('summary.html')!
    expect(summary).toContain('<div class="ring" title="12,000 of 12,345 that ran passed">')
    expect(summary).toContain(
      '<div class="stat-label">Tests</div><div class="stat-total">12,345</div><div class="legend"><span class="s-passed"><i></i>12,000 passed</span><span class="s-failed"><i></i>345 failed</span>'
    )
    expect(summary).toContain(
      '<div class="stat-total">1,000,000</div><div class="legend"><span class="s-passed"><i></i>999,999 passed</span>'
    )
    expect(summary).toContain('title="4,000,000 ms">1&nbsp;hour 6&nbsp;minutes 40.00&nbsp;seconds')
  })

  it('gives each collection page its docs, file, stats and a way back', () => {
    const page = pages(
      run({
        ...collection('smoke', [result('list')]),
        docs: 'Objective: **smoke** the <API>.\n\n- one [link](https://x.test)\n- `two` [bad](javascript:alert(1))'
      })
    ).get('smoke.html')!
    expect(page).toContain(
      '<nav class="crumbs"><a href="summary.html">Summary</a><span aria-hidden="true">/</span><span>smoke</span></nav>'
    )
    expect(page).toContain('<h1>smoke</h1>')
    expect(page).toContain('<code class="file">collections/smoke.yml</code>')
    // Markdown, as the app renders it, with everything escaped and only http(s) links.
    expect(page).toContain('<p class="md-p">Objective: <strong>smoke</strong> the &lt;API&gt;.</p>')
    expect(page).toContain(
      '<li>one <a href="https://x.test" target="_blank" rel="noreferrer noopener">link</a></li>'
    )
    expect(page).toContain(
      '<li><code class="md-inline-code">two</code> bad (javascript:alert(1))</li>'
    )
    expect(page).not.toContain('href="javascript')
    expect(page).toContain('<div class="stat-label">Tests</div>')
    expect(page).toContain('<div class="stat-label">Assertions</div>')
    // Its run time is in its stats, in words, as the summary has the run's; the head says when.
    expect(page).toContain(
      '<div class="stat-label">Total Run Time</div><div class="stat-time" title="10 ms">0.01&nbsp;seconds</div>'
    )
    expect(page).toMatch(/<div class="meta"><span>[^<]+<\/span><\/div>/)
  })

  it('marks the thousands in a collection page’s overview, iterations and stats alike', () => {
    const base = collection('rows', [result('x')], true, {
      steps: { total: 2_468, passed: 2_468, failed: 0, errored: 0, skipped: 0 },
      assertions: { total: 9_876, passed: 9_876, failed: 0 }
    })
    const page = pages(
      run({
        ...base,
        durationMs: 125_004,
        outcome: base.outcome.ok
          ? { ...base.outcome, data: { file: 'data/users.csv', rows: 1_234 } }
          : base.outcome
      })
    ).get('rows.html')!
    expect(page).toContain('<div><dt>Iterations</dt><dd>1,234</dd></div>')
    expect(page).toContain('<div class="stat-total">2,468</div>')
    expect(page).toContain('<i></i>9,876 passed</span>')
    expect(page).toContain('title="125,004 ms">2&nbsp;minutes 5.00&nbsp;seconds')
  })

  it('opens failed tests, with each failed assertion’s expected and actual', () => {
    const page = pages(
      run(
        collection(
          'bad',
          [
            result('fine'),
            result('broken', {
              status: 'fail',
              assertions: [
                {
                  name: 'Status is 201',
                  status: 'fail',
                  message: 'Expected 201, got 200',
                  expected: 'is 201',
                  actual: '200',
                  source: { script: 'step', line: 2 }
                }
              ]
            })
          ],
          false
        )
      )
    ).get('bad.html')!
    expect(page).toContain('<title>FAILED · bad · gta Collection Results</title>')
    expect(page).toMatch(
      /<details class="test s-passed" id="t1" data-status="passed" data-search="fine">\n<summary><span class="n">1<\/span><span class="method m-get">GET<\/span><span class="name">fine<\/span>/
    )
    expect(page).toMatch(
      /<details class="test s-failed" id="t2" data-status="failed" data-search="broken" open>/
    )
    expect(page).toContain('<h3>Request</h3>')
    expect(page).toContain('<h3>Response</h3>')
    expect(page).toContain('<h3>Assertions <span class="dim">1 · 0 passed · 1 failed</span></h3>')
    expect(page).toContain(
      '<li class="s-failed"><span class="mark s-failed" role="img" aria-label="failed">✕</span><div class="check"><div class="check-name">Status is 201</div><div class="check-msg">Expected 201, got 200</div><dl class="ea"><dt>expected</dt><dd><code>is 201</code></dd><dt>actual</dt><dd><code>200</code></dd></dl></div><span class="src">tests:2</span></li>'
    )
    expect(page).toContain('data-hide="passed"')
    expect(page).toContain('data-hide="failed"')
    expect(page).toContain('placeholder="Search tests"')
    // A passed test starts closed, so the button offers to expand.
    expect(page).toContain('<button type="button" class="btn" id="expand-all">Expand All</button>')
  })

  it('names a request a named use step ran by the use step, and searches by that name', () => {
    const page = pages(
      run(
        collection('users', [
          result('get profile', { use: { set: 'create-user', name: 'User 1', child: 1, of: 3 } })
        ])
      )
    ).get('users.html')!
    expect(page).toContain('data-search="user 1 › get profile"')
    expect(page).toContain(
      '<span class="name">User 1 › get profile <span class="dim">(create-user 2/3)</span></span>'
    )
  })

  it('shows a skipped step’s reason, whatever skipped it, and names setup and forEach steps', () => {
    const page = pages(
      run(
        collection('seed', [
          result('grant', { stage: 'setup' }),
          result('approve', {
            status: 'skipped',
            response: null,
            assertions: [],
            skipped: { reason: 'no domains to add for this row' }
          }),
          result('revoke', { stage: 'teardown', forEach: { index: 1, of: 2, item: 'r2' } })
        ])
      )
    ).get('seed.html')!
    expect(page).toContain('<span class="name">setup › grant</span>')
    expect(page).toContain(
      '<p class="skip-reason">no domains to add for this row — this test was not run</p>'
    )
    expect(page).not.toContain('Feature Flag<')
    expect(page).toContain('<span class="name">teardown › revoke (item 2 of 2)</span>')
  })

  it('shows a test’s error first, errored tests counting as failed for the Failed chip', () => {
    const page = pages(
      run(
        collection(
          'a',
          [
            result('login', {
              status: 'error',
              error: { phase: 'tests', message: 'SyntaxError: nope', script: 'step', line: 7 }
            })
          ],
          false
        )
      )
    ).get('a.html')!
    expect(page).toContain(
      '<details class="test s-errored" id="t1" data-status="failed" data-search="login" open>'
    )
    // Every test starts open, so the button offers to collapse.
    expect(page).toContain('id="expand-all">Collapse All</button>')
    expect(page).toContain(
      '<section class="sub problem"><h3>Tests Error</h3><pre>(step script, line 7) SyntaxError: nope</pre></section>'
    )
    expect(page.indexOf('Tests Error')).toBeLessThan(page.indexOf('<h3>Request</h3>'))
  })

  it('shows request and response formatted, and raw as the app’s Console does', () => {
    const page = pageFor(
      result('create', {
        request: {
          method: 'POST',
          url: 'http://x/items',
          headers: [{ name: 'content-type', value: 'application/json' }],
          body: '{"name":"a"}'
        }
      })
    )
    // Formatted: the body pretty and coloured, each part with its own Copy.
    expect(page).toContain(
      '<span class="method m-post">POST</span><code class="url">http://x/items</code><button type="button" class="btn sm" data-copy="url">Copy URL</button>'
    )
    expect(page).toContain(
      '<span class="tx">  <span class="j-k">&quot;name&quot;</span>: <span class="j-s">&quot;a&quot;</span></span>'
    )
    expect(page).toContain(
      '<span class="tx">  <span class="j-k">&quot;id&quot;</span>: <span class="j-n">1</span></span>'
    )
    for (const part of ['headers', 'body', 'raw']) expect(page).toContain(`data-copy="${part}"`)
    // Raw: the one copy of each that every Copy reads, as sent and as received.
    expect(page).toContain(
      '<pre class="raw" data-raw>POST http://x/items\ncontent-type: application/json\n\n{&quot;name&quot;:&quot;a&quot;}</pre>'
    )
    expect(page).toContain(
      '<pre class="raw" data-raw id="t1-raw">200 OK\ncontent-type: application/json\n\n{&quot;id&quot;:1}</pre>'
    )
  })

  it('escapes everything it shows', () => {
    const page = pageFor(
      result('<script>alert(1)</script>', {
        request: { method: 'POST', url: 'http://x/?a=1&b=2', headers: [], body: '<b>' }
      })
    )
    expect(page).toContain('&lt;script&gt;alert(1)&lt;/script&gt;')
    expect(page).not.toContain('<script>alert(1)')
    expect(page).toContain('http://x/?a=1&amp;b=2')
    expect(page).toContain('<span class="tx">&lt;b&gt;</span>')
    expect(page).toContain('\n\n&lt;b&gt;</pre>')
  })

  it('marks each body line as the app does, a failed check’s message beside its line', () => {
    const page = pageFor(
      result('count', {
        status: 'fail',
        response: response({ body: '{"n":1,"m":2}' }),
        assertions: [
          {
            name: 'n is 2',
            status: 'fail',
            target: 'body',
            path: 'n',
            covered: ['n'],
            message: 'Expected 2, got 1'
          },
          { name: 'm is 2', status: 'pass', target: 'body', path: 'm', covered: ['m'] }
        ]
      })
    )
    expect(page).toContain(
      '<div class="ln mk-fail"><span class="no">2</span><span class="mk" aria-hidden="true">✗</span><span class="tx">  <span class="j-k">&quot;n&quot;</span>: <span class="j-n">1</span>,<span class="note">✗ Expected 2, got 1</span></span></div>'
    )
    expect(page).toContain(
      '<div class="ln mk-pass"><span class="no">3</span><span class="mk" aria-hidden="true">✓</span>'
    )
  })

  it('renders an HTML body in a frame with no permissions, filled by the page once shown', () => {
    const html = '<html><body><h1>502 Bad Gateway</h1></body></html>'
    const page = pageFor(
      result('gateway', {
        response: response({
          status: 502,
          statusText: 'Bad Gateway',
          headers: [{ name: 'content-type', value: 'text/html' }],
          body: html,
          bodyKind: 'html'
        })
      })
    )
    expect(page).toContain(
      '<iframe sandbox="" title="The response body, rendered" data-from="t1-raw" data-body></iframe>'
    )
    // The page never writes it into the frame itself: the script does, behind a policy that loads nothing.
    expect(page).not.toContain('srcdoc=')
    expect(page).toContain(`content="default-src \\'none\\'; img-src data:;`)
    expect(page).toContain(
      '<div data-part="source" hidden><div class="codeview"><div class="ln"><span class="no">1</span><span class="mk" aria-hidden="true"></span><span class="tx">&lt;html&gt;'
    )
  })

  it('offers to view HTML and data: images held in a JSON body', () => {
    const image = `data:image/png;base64,${'A'.repeat(200)}==`
    const page = pageFor(
      result('email', {
        response: response({
          body: JSON.stringify({ html: '<p>Hi <b>Pat</b></p>', logo: image, note: 'a < b' })
        })
      })
    )
    expect(page).toContain(
      '<button type="button" class="peek" data-peek="t1-raw-v1" aria-expanded="false">View HTML</button>'
    )
    expect(page).toContain('<div class="peek-row" id="t1-raw-v1" hidden>')
    expect(page).toContain(
      '<pre class="raw" data-part="source" id="t1-raw-v1-source" hidden>&lt;p&gt;Hi &lt;b&gt;Pat&lt;/b&gt;&lt;/p&gt;</pre>'
    )
    expect(page).toContain(
      '<button type="button" class="peek" data-peek="t1-raw-v2" aria-expanded="false">View image</button>'
    )
    expect(page).toContain(`<img loading="lazy" src="${image}" alt="The image at logo">`)
    // Shortened on its line; Raw and Copy keep all of it.
    expect(page).toContain(`&quot;${image.slice(0, 40)}…&quot;`)
    // Text with a < in it is not markup.
    expect(page).not.toContain('data-peek="t1-raw-v3"')
  })

  it('shows an image body as the image, its raw text saying what there was as the Console does', () => {
    const png =
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='
    const page = pageFor(
      result('logo', {
        response: response({
          headers: [{ name: 'content-type', value: 'image/png' }],
          body: png,
          bodyKind: 'binary',
          bodyEncoding: 'base64',
          sizeBytes: 70
        })
      })
    )
    expect(page).toContain(
      `<img loading="lazy" src="data:image/png;base64,${png}" alt="The response body">`
    )
    expect(page).toContain(
      '<button type="button" class="btn sm" data-copy="image">Copy data URI</button>'
    )
    expect(page).toContain('content-type: image/png\n\n[binary body, 70 B]</pre>')
    // Neither the body's Copy nor its base64 in Raw: the image is the one copy.
    expect(page).not.toContain('data-copy="body"')
    expect(page.split(png)).toHaveLength(2)
  })

  it('offers any other binary body to download, and leaves out one too big for the page', () => {
    const pdf = (sizeBytes: number) =>
      pageFor(
        result('statement', {
          response: response({
            headers: [{ name: 'content-type', value: 'application/pdf' }],
            body: 'JVBERi0xLjc=',
            bodyKind: 'binary',
            bodyEncoding: 'base64',
            sizeBytes
          })
        })
      )
    expect(pdf(8)).toContain(
      '<a class="btn sm" href="data:application/pdf;base64,JVBERi0xLjc=" download="t1-body.pdf">Download</a>'
    )
    const big = pdf(2 * 1024 * 1024)
    expect(big).toContain('Over 1.0 MB, too big to put in the report.')
    expect(big).not.toContain('JVBERi0xLjc=')
  })

  it('shows a binary type whose bytes are text as that text', () => {
    const page = pageFor(
      result('token', {
        response: response({
          headers: [{ name: 'content-type', value: 'application/jwt' }],
          body: 'eyJhbGciOiJub25lIn0.e30.',
          bodyKind: 'binary'
        })
      })
    )
    expect(page).toContain('<pre class="raw">eyJhbGciOiJub25lIn0.e30.</pre>')
    expect(page).toContain('content-type: application/jwt\n\neyJhbGciOiJub25lIn0.e30.</pre>')
  })

  it('shows an event stream as its events, with how many and what stopped it', () => {
    const stream = 'event: price\ndata: {"price":100}\n\n: heartbeat\n\ndata: [DONE]\n\n'
    const page = pageFor(
      result('prices', {
        response: response({
          headers: [{ name: 'content-type', value: 'text/event-stream' }],
          body: stream,
          bodyKind: 'events',
          sizeBytes: stream.length,
          stream: { endedBy: 'maxEvents', at: [3, 9] }
        })
      })
    )
    expect(page).toContain('text/event-stream · 61 B · read as events')
    expect(page).toContain(
      '<span class="j-k">&quot;event&quot;</span>: <span class="j-s">&quot;price&quot;</span>'
    )
    expect(page).toContain('2 events, stopped at maxEvents')
  })

  it('says why a collection did not run', () => {
    const page = pages(
      run({
        id: 'slow',
        file: 'collections/slow.yml',
        startedAt: 0,
        durationMs: 500,
        tally: { ...tallyOf(false), id: 'slow' },
        outcome: { ok: false, message: 'Timed out after 500 ms (timeoutCollection)' }
      })
    ).get('slow.html')!
    expect(page).toContain(
      '<section class="sub problem"><h3>Error</h3><pre>Timed out after 500 ms (timeoutCollection)</pre></section>'
    )
    expect(page).toContain('<p class="dim empty">No tests were run.</p>')
  })

  it('cuts a very large body, formatted and raw, saying how much is missing', () => {
    const big = 'x'.repeat(300 * 1024)
    const page = pageFor(
      result('big', { response: response({ bodyKind: 'text', body: big, sizeBytes: big.length }) })
    )
    expect(page.match(/44\.0 KB more not shown/g)).toHaveLength(2)
    // Neither view holds more of it than the limit.
    expect(Math.max(...page.match(/x+/g)!.map((run) => run.length))).toBe(256 * 1024)
  })
})

describe('runTime', () => {
  it('says a run’s time in words, to the hundredth of a second', () => {
    expect(runTime(90_610)).toBe('1 minute 30.61 seconds')
    expect(runTime(381)).toBe('0.38 seconds')
    expect(runTime(0)).toBe('0.00 seconds')
    expect(runTime(1000)).toBe('1.00 seconds')
    expect(runTime(125_004)).toBe('2 minutes 5.00 seconds')
    expect(runTime(7_384_560)).toBe('2 hours 3 minutes 4.56 seconds')
  })

  it('leaves out a unit with none of it, rounding first', () => {
    expect(runTime(60_000)).toBe('1 minute')
    expect(runTime(59_999)).toBe('1 minute')
    expect(runTime(3_600_000)).toBe('1 hour')
    expect(runTime(3_605_000)).toBe('1 hour 5.00 seconds')
  })
})
